<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2 on 2023-11-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2 on 2022-12-20 22:47
=======
# Generated by Django 3.2 on 2023-11-07 16:07
>>>>>>> d8cc8ad98 (more)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import django.utils.timezone
>>>>>>> 424a6b920 (first commit)
=======
>>>>>>> d8cc8ad98 (more)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> d8cc8ad98 (more)
            name='BoardEpi',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
>>>>>>> 424a6b920 (first commit)
=======
>>>>>>> d8cc8ad98 (more)
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> d8cc8ad98 (more)
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Demitido', 'Demitido')], default='Ativo', max_length=20)),
                ('cargo', models.CharField(choices=[('Pintor', 'Pintor'), ('Mestre', 'Mestre'), ('Servente', 'Servente'), ('Auxiliar de Pintor', 'Auxiliar de Pintor'), ('Encarregado de Obras', 'Encarregado de Obras')], default='Pintor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
                ('cardUrl', models.CharField(max_length=100)),
                ('checklist', models.CharField(max_length=100)),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
                ('item4', models.CharField(max_length=100)),
                ('item5', models.CharField(max_length=100)),
                ('item6', models.CharField(max_length=100)),
                ('item7', models.CharField(max_length=100)),
                ('item8', models.CharField(max_length=100)),
                ('item9', models.CharField(max_length=100)),
                ('item10', models.CharField(max_length=100)),
                ('i1_status', models.CharField(max_length=100)),
                ('i2_status', models.CharField(max_length=100)),
                ('i3_status', models.CharField(max_length=100)),
                ('i4_status', models.CharField(max_length=100)),
                ('i5_status', models.CharField(max_length=100)),
                ('i6_status', models.CharField(max_length=100)),
                ('i7_status', models.CharField(max_length=100)),
                ('i8_status', models.CharField(max_length=100)),
                ('i9_status', models.CharField(max_length=100)),
                ('i10_status', models.CharField(max_length=100)),
                ('i1_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i2_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i3_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i4_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i5_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i6_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i7_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i8_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i9_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i10_user', models.CharField(blank=True, max_length=100, null=True)),
                ('i1_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i2_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i3_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i4_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i5_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i6_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i7_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i8_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i9_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i10_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
>>>>>>> 424a6b920 (first commit)
=======
>>>>>>> d8cc8ad98 (more)
            name='UpdateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True, help_text='Date of the creation', verbose_name='Creation date')),
                ('trello_request', models.FloatField(default=0, null=True)),
                ('data_input', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.board')),
                ('pintor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor1', to='blog.colaborador')),
                ('pintor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor2', to='blog.colaborador')),
                ('pintor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor3', to='blog.colaborador')),
                ('pintor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor4', to='blog.colaborador')),
            ],
=======
            name='Post',
=======
            name='Equipe',
>>>>>>> d8cc8ad98 (more)
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.board')),
                ('pintor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor1', to='blog.colaborador')),
                ('pintor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor2', to='blog.colaborador')),
                ('pintor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor3', to='blog.colaborador')),
                ('pintor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pintor4', to='blog.colaborador')),
            ],
<<<<<<< HEAD
            options={
                'ordering': ('-published',),
            },
>>>>>>> 424a6b920 (first commit)
=======
>>>>>>> d8cc8ad98 (more)
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('card', models.CharField(max_length=100)),
                ('card2', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('macro', models.CharField(default=None, max_length=100, null=True)),
=======
>>>>>>> 424a6b920 (first commit)
=======
                ('macro', models.CharField(default=None, max_length=100, null=True)),
>>>>>>> d8cc8ad98 (more)
                ('cardUrl', models.CharField(max_length=100)),
                ('cardActive', models.CharField(max_length=100)),
                ('checklist', models.CharField(max_length=100)),
                ('pacote', models.CharField(max_length=100)),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
                ('item4', models.CharField(max_length=100)),
                ('item5', models.CharField(max_length=100)),
                ('i1_status', models.CharField(max_length=100)),
                ('i2_status', models.CharField(max_length=100)),
                ('i3_status', models.CharField(max_length=100)),
                ('i4_status', models.CharField(max_length=100)),
                ('i5_status', models.CharField(max_length=100)),
                ('i1_user', models.CharField(max_length=100)),
                ('i2_user', models.CharField(max_length=100)),
                ('i3_user', models.CharField(max_length=100)),
                ('i4_user', models.CharField(max_length=100)),
                ('i5_user', models.CharField(max_length=100)),
                ('i1_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i2_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i3_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i4_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i5_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i1_data', models.CharField(max_length=100)),
                ('i2_data', models.CharField(max_length=100)),
                ('i3_data', models.CharField(max_length=100)),
                ('med', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('complete', models.IntegerField()),
<<<<<<< HEAD
<<<<<<< HEAD
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.board')),
=======
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.board')),
>>>>>>> 424a6b920 (first commit)
=======
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.board')),
>>>>>>> d8cc8ad98 (more)
            ],
        ),
    ]
